### PR TITLE
Lockette fixes, LockettePro support

### PR DESCRIPTION
**Pull request by IAISI**

### CODE REVIEW

**Review by Sfiguz7 — DISMISSED** [review]

**Comment by Sfiguz7** [comment]
The dependency is not being found, could you double check if it's correct please?

**Comment by IAISI** [comment]
It should be updated fork of https://github.com/connection-lost/LockettePro

probably...

https://github.com/NyaaCat/LockettePro
https://github.com/GreenSurvivors/LockettePro
https://github.com/233Chad/LockettePro

personally I'm using the one from NyanCat, also the one from 233Chad is good, they all use same package names.

**Comment by IAISI** [comment]
My bad I just realized I'm using 233Chad's version.

**Review by J3fftw1 — CHANGES_REQUESTED** [review]
You are using com.github.NyaaCat this is api dependency but you use me.crafter.mc.lockettepro. This will cause errors.

**Comment by IAISI** [comment]
This should fix the issue.

**Comment by IAISI** [comment]
Would also like to point out that the I suspect original Lockette implementation is wrong:

https://github.com/baked-libs/dough/blob/main/dough-protection/src/main/java/io/github/bakedlibs/dough/protection/modules/LocketteProtectionModule.java

´´´
    @Override
    public boolean hasPermission(OfflinePlayer p, Location l, Interaction action) {
        if (action.getType() != ActionType.BLOCK) {
            return true;
        }

        Block b = l.getBlock();

        if (Lockette.isProtected(b)) {
            BlockState state = b.getState();

            if (state instanceof Sign) {
                return !Lockette.isOwner((Sign) state, p);
            } else {
                return !Lockette.isOwner(b, p);
            }
        } else
            return false;
    }
´´´

If block is NOT protected by lockette is would always return false for hasPermission, this is probably not right?

**Comment by J3fftw1** [comment]
> Would also like to point out that the I suspect original Lockette implementation is wrong:
> 
> [`main`/dough-protection/src/main/java/io/github/bakedlibs/dough/protection/modules/LocketteProtectionModule.java](https://github.com/baked-libs/dough/blob/main/dough-protection/src/main/java/io/github/bakedlibs/dough/protection/modules/LocketteProtectionModule.java?rgh-link-date=2023-12-14T09%3A54%3A47Z)
> 
> ` @OverRide public boolean hasPermission(OfflinePlayer p, Location l, Interaction action) { if (action.getType() != ActionType.BLOCK) { return true; }
> 
> ```
>     Block b = l.getBlock();
> 
>     if (Lockette.isProtected(b)) {
>         BlockState state = b.getState();
> 
>         if (state instanceof Sign) {
>             return !Lockette.isOwner((Sign) state, p);
>         } else {
>             return !Lockette.isOwner(b, p);
>         }
>     } else
>         return false;
> }
> ```
> 
> `
> 
> If block is NOT protected by lockette is would always return false for hasPermission, this is probably not right?
> 
> Furthermore booleans are also wrongly negated? So if Lockette#isOwner returns true, hasPermission would actually return false?

What you are saying could very well be true, This is why i said on discord to you we do not implement these things since we do not know how their stuff works.
This might very well be case of a user like you implementing this wrongly and since we do not the implementation these issues would arrise

**Comment by IAISI** [comment]
https://github.com/NyaaCat/LockettePro/blob/1.20.1/src/main/java/me/crafter/mc/lockettepro/LocketteProAPI.java

I understand, sorry for the confusion, I guess I can just close this?

**Comment by J3fftw1** [comment]
You dont have to close this we appreciate the PR.
We just need to be sure its working.

**Comment by J3fftw1** [comment]
Marking this as stale.
The repo is no merged to the Slimefun org so it should be reviewed faster in the future.

**Pull request closed without merging**
